# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(486, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boud_list = QtWidgets.QComboBox(self.centralwidget)
        self.boud_list.setGeometry(QtCore.QRect(120, 360, 131, 22))
        self.boud_list.setObjectName("boud_list")
        self.boud_list.addItem("")
        self.boud_list.addItem("")
        self.boud_list.addItem("")
        self.boud_list.addItem("")
        self.label_USD_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_USD_2.setGeometry(QtCore.QRect(20, 360, 41, 23))
        self.label_USD_2.setObjectName("label_USD_2")
        self.label_USD_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_USD_3.setGeometry(QtCore.QRect(20, 330, 41, 23))
        self.label_USD_3.setObjectName("label_USD_3")
        self.box_ports = QtWidgets.QComboBox(self.centralwidget)
        self.box_ports.setGeometry(QtCore.QRect(120, 330, 131, 22))
        self.box_ports.setObjectName("box_ports")
        self.btn_portScan = QtWidgets.QPushButton(self.centralwidget)
        self.btn_portScan.setGeometry(QtCore.QRect(270, 330, 75, 23))
        self.btn_portScan.setObjectName("btn_portScan")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 40, 421, 261))
        self.widget.setObjectName("widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 486, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuopen = QtWidgets.QMenu(self.menu)
        self.menuopen.setObjectName("menuopen")
        MainWindow.setMenuBar(self.menubar)
        self.actionfile = QtWidgets.QAction(MainWindow)
        self.actionfile.setObjectName("actionfile")
        self.actionfolder = QtWidgets.QAction(MainWindow)
        self.actionfolder.setObjectName("actionfolder")
        self.menuopen.addAction(self.actionfile)
        self.menuopen.addAction(self.actionfolder)
        self.menu.addAction(self.menuopen.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boud_list.setItemText(0, _translate("MainWindow", "9600"))
        self.boud_list.setItemText(1, _translate("MainWindow", "19200"))
        self.boud_list.setItemText(2, _translate("MainWindow", "38400"))
        self.boud_list.setItemText(3, _translate("MainWindow", "115200"))
        self.label_USD_2.setText(_translate("MainWindow", "波特率"))
        self.label_USD_3.setText(_translate("MainWindow", "串口"))
        self.btn_portScan.setText(_translate("MainWindow", "检测"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menuopen.setTitle(_translate("MainWindow", "open"))
        self.actionfile.setText(_translate("MainWindow", "file"))
        self.actionfolder.setText(_translate("MainWindow", "folder"))
