# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(486, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_header = QtWidgets.QLabel(self.centralwidget)
        self.label_header.setGeometry(QtCore.QRect(60, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setObjectName("label_header")
        self.boud_list = QtWidgets.QComboBox(self.centralwidget)
        self.boud_list.setGeometry(QtCore.QRect(160, 200, 131, 22))
        self.boud_list.setObjectName("boud_list")
        self.boud_list.addItem("")
        self.boud_list.addItem("")
        self.label_USD_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_USD_2.setGeometry(QtCore.QRect(60, 200, 41, 23))
        self.label_USD_2.setObjectName("label_USD_2")
        self.label_USD_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_USD_3.setGeometry(QtCore.QRect(60, 170, 41, 23))
        self.label_USD_3.setObjectName("label_USD_3")
        self.port_list = QtWidgets.QComboBox(self.centralwidget)
        self.port_list.setGeometry(QtCore.QRect(160, 170, 131, 22))
        self.port_list.setObjectName("port_list")
        self.btn_portScan = QtWidgets.QPushButton(self.centralwidget)
        self.btn_portScan.setGeometry(QtCore.QRect(310, 170, 75, 23))
        self.btn_portScan.setObjectName("btn_portScan")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(60, 110, 377, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.inputEdit = QtWidgets.QLineEdit(self.splitter)
        self.inputEdit.setObjectName("inputEdit")
        self.label_USD = QtWidgets.QLabel(self.splitter)
        self.label_USD.setObjectName("label_USD")
        self.btn_transform = QtWidgets.QPushButton(self.splitter)
        self.btn_transform.setObjectName("btn_transform")
        self.outputEdit = QtWidgets.QLineEdit(self.splitter)
        self.outputEdit.setObjectName("outputEdit")
        self.label_CNY = QtWidgets.QLabel(self.splitter)
        self.label_CNY.setObjectName("label_CNY")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 486, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuopen = QtWidgets.QMenu(self.menu)
        self.menuopen.setObjectName("menuopen")
        MainWindow.setMenuBar(self.menubar)
        self.actionfile = QtWidgets.QAction(MainWindow)
        self.actionfile.setObjectName("actionfile")
        self.actionfolder = QtWidgets.QAction(MainWindow)
        self.actionfolder.setObjectName("actionfolder")
        self.menuopen.addAction(self.actionfile)
        self.menuopen.addAction(self.actionfolder)
        self.menu.addAction(self.menuopen.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_header.setText(_translate("MainWindow", "汇率转换器"))
        self.boud_list.setItemText(0, _translate("MainWindow", "9600"))
        self.boud_list.setItemText(1, _translate("MainWindow", "115200"))
        self.label_USD_2.setText(_translate("MainWindow", "波特率"))
        self.label_USD_3.setText(_translate("MainWindow", "串口"))
        self.btn_portScan.setText(_translate("MainWindow", "检测"))
        self.label_USD.setText(_translate("MainWindow", "USD"))
        self.btn_transform.setText(_translate("MainWindow", "转换"))
        self.label_CNY.setText(_translate("MainWindow", "CNY"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menuopen.setTitle(_translate("MainWindow", "open"))
        self.actionfile.setText(_translate("MainWindow", "file"))
        self.actionfolder.setText(_translate("MainWindow", "folder"))
